FROM tomcat:8.0-jre8

# install Bioscholar from Github (NOT FROM A LOCAL FILE).  

RUN wget -O /usr/local/tomcat/webapps/bioscholar.war "https://github.com/BMKEG/bioscholar/releases/download/v1.1.5/bioscholar.war"
    
