version: '3'

services:
  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: Dttef99
      MYSQL_DATABASE: evidx
    ports:
     - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
  web:
    build:
      context: tomcat
      dockerfile: Dockerfile   
    ports:
     - "80:8080"
    volumes:
     - ./tomcat/webapps:/usr/local/tomcat/webapps
     - ./bmkeg/:/root/bmkeg
    links:
     - db
