version: '3'

services:
  db:
    image: mysql:5.5
    command: --max_allowed_packet=32505856 
    environment:
      MYSQL_ROOT_PASSWORD: Dttef99
      MYSQL_DATABASE: evidx
      MYSQL_USER: root
    ports:
     - "3306:3306"
    volumes:
      - ./db:/root/dbscripts
      #- ./data:/var/lib/mysql
  web:
    build:
      context: tomcat
      dockerfile: Dockerfile   
    ports:
     - "80:8080"
    volumes:
     - ./tomcat/webapps:/usr/local/tomcat/webapps
     - ./bmkeg/:/root/bmkeg
     - ./bmkeg/:/root/bmkeg
     - /Users/Gully/Documents/Projects/2_active/bigMech/wd:/root/workingDirectory
    links:
     - db
